name: Rancher Google
description: |
  Docker volume plugin for GStorage.
version: 0.5.0
category: Storage
labels:
  io.rancher.certified: rancher
  io.rancher.orchestration.supported: 'cattle,mesos,swarm'