.catalog:
  name: "REX-Ray DigitalOcean"
  version: "v0.9.0"
  description: |
    Docker volume plugin for DigitalOcean
  questions:
    - variable: GSTORAGE_TOKEN
      type: string
      required: true
      label: Google Storage Token
      description: JSON Token
    - variable: DEFAULT_BUCKET
      type: string
      required: true
      label: Google Storage Bucket
      description: Bucket a ser usado
    - variable: RANCHER_DEBUG
      type: enum
      required: true
      default: false
      options:
      - true
      - false
      label: Debug Mode
      description: Enable or disable verbose logging

google-storage-driver:
  storage_driver:
    name: google-storage
    scope: environment
    volume_access_mode: singleHostRW
