version: '2'
services:
  useradm-secrets:
    image: gustavosbarreto/mender-secrets-provider
    environment:
      USERADM_SERVER_PRIV_KEY_SECRET: '${USERADM_SERVER_PRIV_KEY_SECRET}'
    stdin_open: true
    volumes:
    - /run/secrets
    tty: true
    links:
    - mongo-useradm:mongo-useradm
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
  useradm:
    image: mendersoftware/useradm:1.0.0
    environment:
      USERADM_SERVER_PRIV_KEY_PATH: /run/secrets/USERADM_SERVER_PRIV_KEY
    stdin_open: true
    tty: true
    links:
    - mongo-useradm:mongo-useradm
    volumes_from:
    - useradm-secrets
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: useradm-secrets
  mongo-device-auth:
    image: mongo:3.4
    stdin_open: true
    volume_driver: '${MENDER_VOLUME_DRIVER}'
    volumes:
    - deviceauth:/data/db
    tty: true
    labels:
      io.rancher.container.pull_image: always
  mongo-deployments:
    image: mongo:3.4
    stdin_open: true
    tty: true
    volume_driver: '${MENDER_VOLUME_DRIVER}'
    volumes:
    - deployments:/data/db
    labels:
      io.rancher.container.pull_image: always
  inventory:
    image: mendersoftware/inventory:1.0.0
    stdin_open: true
    tty: true
    links:
    - mongo-inventory:mongo-inventory
    labels:
      io.rancher.container.pull_image: always
  device-adm:
    image: mendersoftware/deviceadm:1.0.0
    environment:
      DEVICEADM_DEVAUTHURL: http://device-auth:8080
    stdin_open: true
    tty: true
    links:
    - mongo-device-adm:mongo-device-adm
    labels:
      io.rancher.container.pull_image: always
  deployments:
    image: mendersoftware/deployments:1.0.1
    environment:
      DEPLOYMENTS_AWS_AUTH_KEY: '${DEPLOYMENTS_S3_ACCESS_KEY}'
      DEPLOYMENTS_AWS_AUTH_SECRET: '${DEPLOYMENTS_S3_SECRET_KEY}'
      DEPLOYMENTS_AWS_BUCKET: '${DEPLOYMENTS_S3_BUCKET_KEY}'
      DEPLOYMENTS_AWS_URI: '${DEPLOYMENTS_S3_URI}'
      DEPLOYMENTS_MENDER_GATEWAY: http://inventory:8080
    stdin_open: true
    tty: true
    links:
    - mongo-deployments:mongo-deployments
    labels:
      io.rancher.container.pull_image: always
  mongo-device-adm:
    image: mongo:3.4
    stdin_open: true
    volume_driver: '${MENDER_VOLUME_DRIVER}'
    volumes:
    - deviceadm:/data/db
    tty: true
    labels:
      io.rancher.container.pull_image: always
  lb:
    image: rancher/lb-service-haproxy:v0.7.5
    ports:
    - 80:80/tcp
    - 443:443/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: true
  api-gateway:
    image: gustavosbarreto/mender-api-gateway
    stdin_open: true
    tty: true
    links:
    - deployments:mender-deployments
    - gui:mender-gui
    - device-auth:mender-device-auth
    - inventory:mender-inventory
    - useradm:mender-useradm
    - device-adm:mender-device-adm
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: true
  device-auth-secrets:
    image: gustavosbarreto/mender-secrets-provider
    environment:
      DEVICEAUTH_SERVER_PRIV_KEY_SECRET: '${DEVICEAUTH_SERVER_PRIV_KEY_SECRET}'
    stdin_open: true
    volumes:
    - /run/secrets
    tty: true
    links:
    - mongo-device-auth:mongo-device-auth
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
  gui:
    image: mendersoftware/gui:1.0.1
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  mongo-useradm:
    image: mongo:3.4
    stdin_open: true
    volume_driver: '${MENDER_VOLUME_DRIVER}'
    volumes:
    - useradm:/data/db
    tty: true
    labels:
      io.rancher.container.pull_image: always
  mongo-inventory:
    image: mongo:3.4
    stdin_open: true
    volume_driver: '${MENDER_VOLUME_DRIVER}'
    volumes:
    - inventory:/data/db
    tty: true
    labels:
      io.rancher.container.pull_image: always
  device-auth:
    image: mendersoftware/deviceauth:1.0.0
    environment:
      DEVICEAUTH_SERVER_PRIV_KEY_PATH: /run/secrets/DEVICEAUTH_SERVER_PRIV_KEY
      DEVICEAUTH_DEVADM_ADDR: http://device-adm:8080
      DEVICEAUTH_INVENTORY_ADDR: http://inventory:8080
    stdin_open: true
    tty: true
    links:
    - mongo-device-auth:mongo-device-auth
    volumes_from:
    - device-auth-secrets
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: device-auth-secrets
