name: Mender 
description: |
  Over-the-air software updates for embedded Linux devices
version: v1.0.1
category: OTA
maintainer: Luis Gustavo S. Barreto <gustavosbarreto@gmail.com>
projectURL: http://github.com/gustavosbarreto/mender-rancher
labels:
  io.rancher.orchestration.supported: 'cattle,swarm'
