version: '2'

services:
  google-storage-driver:
    image: smscsite/app:storage-google
    privileged: true
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
      - /run:/run
      - /var/run:/var/run
      - /dev:/host/dev
      - /var/lib/rancher/volumes:/var/lib/rancher/volumes:shared
    environment:
      GSTORAGE_TOKEN: '${GSTORAGE_TOKEN}'
      DEFAULT_BUCKET: '${DEFAULT_BUCKET}'
      RANCHER_DEBUG: '${RANCHER_DEBUG}'
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: true
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environment
